name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: .

      - name: Run unit tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=src tests/unit
        working-directory: .
        env:
          CONNECT_STRING: ${{ secrets.CONNECT_STRING }}
          PORT: ${{ secrets.PORT }}
          EXP_DATE: ${{ secrets.EXP_DATE }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          SALT_KEY: ${{ secrets.SALT_KEY }}

  bdd-test:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt behave
        working-directory: .

      - name: Start server
        run: |
          python server.py &
          for i in {1..10}; do
            if curl -s http://localhost:8000/health; then
              break
            fi
            sleep 2
          done
        env:
          CONNECT_STRING: ${{ secrets.CONNECT_STRING }}
          PORT: ${{ secrets.PORT }}
          EXP_DATE: ${{ secrets.EXP_DATE }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          SALT_KEY: ${{ secrets.SALT_KEY }}

      - name: Run BDD tests
        run: |
          behave tests/bdd/features/create_user.feature && behave tests/bdd/features/auth_check.feature && behave tests/bdd/features/auth_verify.feature
